### ISSUE TITLE
API failures

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/utilix#36]
Sometimes, API calls fail because of the authentication using the ~/.dbtoken:
```python
Traceback (most recent call last):
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/bin/admix-download", line 8, in <module>
    sys.exit(main())
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/admix/download.py", line 257, in main
    hash = utilix.db.get_hash(args.context, args.dtype, version)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/utilix/rundb.py", line 398, in get_hash
    response = json.loads(self._get(url).text)
  File "/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/utilix/rundb.py", line 124, in func_wrapper
    raise RuntimeError("API call failed.")
RuntimeError: API call failed.
```

Perhaps one of the causes could be different utilix configs. When I run in the container, I use another config then when I'm using my own conda installation. Could this cause the issue?

**Comment by ershockley** [comment]
Hi Joran, thanks for making the issue. I also hit this error quite often but have just not had a chance to debug it fully yet. It seems to be related to switching between users, where I guess the token-user pair doesn't get updated correctly? I will try to work on this today.

**Comment by jorana** [comment]
Not urgent, but I just noticed that it indeed is probably related to the different users, hence I made the issue (because my mental notes sometimes get lost)

**Comment by JoranAngevaare** [comment]
Seems solved
